  MODULE('APLIKACIJA001.CLW')
PopisMobitela          PROCEDURE                      !Popis mobitela
PopisMuzike            PROCEDURE                      !Popis muzike
PopisSlika             PROCEDURE                      !Popis slika
PopisVidea             PROCEDURE                      !Popis videa
PopisKartica           PROCEDURE                      !Popis SD kartica
AzuriranjeMobitela     PROCEDURE                      !Azuriranje mobitela
AzuriranjeMuzike       PROCEDURE                      !Azuriranje muzike
AzuriranjeSlika        PROCEDURE                      !Azuriranje slika
AzuriranjeVidea        PROCEDURE                      !Azuriranje videa
  END
