  MODULE('APLIKACIJA002.CLW')
AzuriranjeKartica      PROCEDURE                      !Azuriranje kartica
AzuriranjeImaM         PROCEDURE                      !Azuriranje ImaM
AzuriranjeImaP         PROCEDURE                      !Azuriranje ImaP
AzuriranjeImaV         PROCEDURE                      !Azuriranje ImaV
IspisSlika2            PROCEDURE                      !Ispis slika - jednostavno izvjesce - 1 slika na stranicu
StavkeOdabraneSlike    PROCEDURE                      !Ispis slika - jednostavno izvjesce na gumb
PomocniIspis           PROCEDURE                      !Ispis pjesama u pojedinom mobitelu
IspisSlika1            PROCEDURE                      !Ispis slika - jednostavno izvjesce
SkocniProzor           PROCEDURE                      !Skocni prozor
  END
